version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/gettingStarted/
    command: uvicorn gettingStarted:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file: 
      - ./.env.test
    ports: 
      - 8000:8000
    networks:
      - common
    depends_on:
      - db

  db: 
    image: mysql:8.0.23
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./.env.test
    # environment:
    #  MYSQL_ROOT_PASSWORD: password
    #  MYSQL_DATABASE: gs
    #  MYSQL_USER: root
    #  MYSQL_PASSWORD: gs
    networks:
      - common
networks:
  common:
volumes:
  db_data: